export const NUMBER_OF_DEFAULT_PLAYERS = 2;
export const NUMBER_OF_CARDS_PER_PLAYER = 2;
export const NUMBER_OF_CARDS_FOR_FLOP = 3;
export const NUMBER_OF_CARDS_FOR_TURN = 1;
export const NUMBER_OF_CARDS_FOR_RIVER = 1;
